package de.wasenweg.komix.preferences;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Document
public class Preference {

    @Id
    private String id;

    private String key;
    private String name;
    private String value;
    private String comment;

    // FIXME this should be auto generated by @RequiredArgsConstructor
    public Preference(final String key, final String name, final String value, final String comment) {
        this.key = key;
        this.name = name;
        this.value = value;
        this.comment = comment;
    }
}
