version: '3.7'
services:

  app:
    build:
      context: .
      dockerfile: .Dockerfile.test
      shm_size: '2gb'
    ports:
      - '8080:8080'
    volumes:
      - $PWD/src/test/resources/fixtures/full:/comics
      - /dev/shm:/dev/shm
    environment:
      DOCKER_MODE: 'true'
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATA_MONGODB_URI: mongodb://mongo/alfred

  mongo:
    image: 'mongo:4.2'
    logging:
      driver: none
