services:
  - docker
jobs:
  include:
    - stage: Unit tests
      script:
        - docker-compose -f docker-compose.unit-test.yml up

    - stage: UI tests
      script:
        - docker-compose -f docker-compose.ui-test.yml up --abort-on-container-exit

