version: '3'
services:
  alfred:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - $PWD/src/test/resources/fixtures/full:/comics
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATA_MONGODB_URI: mongodb://mongo/alfred
  mongo:
    image: "mongo:6.0"
