version: '3'
services:

  alfred-ui-test:
    build:
      context: .
      dockerfile: .Dockerfile-ui-test
    environment:
      DOCKER_MODE: 'true'
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - alfred
    command: bash -c "
      echo -n 'Waiting for Spring Boot app ';
      while ! (curl --output /dev/null --silent --head --fail http://alfred:8080); do (echo -n . && sleep 1); done;
      echo ' up!';
      npm run e2eHeadless"

  alfred:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - $PWD/src/test/resources/fixtures/full:/comics
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATA_MONGODB_URI: mongodb://mongo/alfred
    depends_on:
      - mongo
    healthcheck:
      test: curl --output /dev/null --silent --head --fail http://localhost:8080
      interval: 4s
      timeout: 10s
      retries: 4
    logging:
      driver: none

  mongo:
    image: mongo:3.6
    logging:
      driver: none

