spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: mongodb://localhost/alfred
  mongodb:
    embedded:
      version: 3.6.12
      features: NO_HTTP_INTERFACE_ARG

management:
  endpoints:
    web:
      exposure:
        include: '*'

comics:
  path: src/test/resources/fixtures/full
  comicVine:
    baseUrl: http://localhost:1080
