package de.wasenweg.komix.comics;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Document
public class Comic {

    @Id
    private String id;

    private String path;
    private String title;
    private String series;
    private String number;
    private String position;
    private String volume;
    private String summary;
    private String notes;
    private Short year;
    private Short month;
    private String writer;
    private String penciller;
    private String inker;
    private String colorist;
    private String letterer;
    private String coverArtist;
    private String editor;
    private String publisher;
    private String web;
    private Short pageCount;
    private boolean manga;
    private String characters;
    private String teams;
    private byte[] thumbnail;

    @Override
    public String toString() {
        return String.format(
                "Comic[id=%s, series='%s', volume='%s', number='%s']",
                id, series, volume, number);
    }

    // FIXME this should be auto generated by @RequiredArgsConstructor
    public Comic(final String path, final String title, final String series,
            final String number, final String position, final short year,
            final short month, final String publisher) {
        this.path = path;
        this.title = title;
        this.series = series;
        this.number = number;
        this.position = position;
        this.publisher = publisher;
    }
}
