CREATE TABLE COMICS (
  id IDENTITY NOT NULL PRIMARY KEY,
  path CLOB NOT NULL,
  title VARCHAR(255) NOT NULL,
  series VARCHAR(255) NOT NULL,
  number VARCHAR(10) NOT NULL,
  position VARCHAR(6) NOT NULL,
  volume VARCHAR(255),
  summary CLOB,
  notes CLOB,
  year SMALLINT NOT NULL,
  month SMALLINT NOT NULL,
  writer CLOB,
  penciller CLOB,
  inker CLOB,
  colorist CLOB,
  letterer CLOB,
  cover_artist CLOB,
  editor CLOB,
  publisher VARCHAR(255) NOT NULL,
  web CLOB,
  page_count SMALLINT,
  manga BOOLEAN,
  characters CLOB,
  teams CLOB
);
