name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install Java
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Check backend
      run: ./gradlew --build-cache check jacocoTestReport -x :ui:jar

    - name: Upload backend coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./build/reports/jacoco/test/jacocoTestReport.xml

    - name: Check frontend
      working-directory: ui
      run: |
        npm ci --loglevel error
        npm run lint
        npm run testHeadless

    - name: Upload frontend coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./ui/coverage/coverage-final.json

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.1.0
      with:
        mongodb-version: 3.6

    - name: Start Alfred
      run: |
        ./gradlew --build-cache bootRun &> output &
        echo -n "Waiting for boot to complete "
        seconds=0
        while ! curl --output /dev/null --silent --head --fail http://localhost:8080; do
          if [ $seconds -gt 160 ]; then echo -e " timeout reached!\n\n" && cat output && exit 1; fi
          ((seconds++)) && echo -n "." && sleep 2
        done
        echo " done!"
      env:
        SPRING_PROFILES_ACTIVE: test
        COMICS_COMICVINE_APIKEY: foo
        SPRING_DATA_MONGODB_URI: mongodb://localhost/alfred

    - name: Run end-to-end tests
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 15
        max_attempts: 5
        retry_on: error
        command: cd ui && npm run e2eHeadless
