name: Tests

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Unit tests
      run: docker-compose -f docker-compose.unit-test.yml up
  ui-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: UI tests
      run: docker-compose -f docker-compose.ui-test.yml up --abort-on-container-exit

