name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install Java
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install Chrome
      run: |
        curl -sSL https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo 'deb https://dl.google.com/linux/chrome/deb/ stable main' | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends google-chrome-stable fontconfig fonts-ipafont-gothic fonts-freefont-ttf

    - name: Check backend
      run: ./gradlew --build-cache -q check jacocoTestReport -x :ui:jar

    - name: Upload backend coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./build/reports/jacoco/test/jacocoTestReport.xml

    - name: Check frontend
      working-directory: ui
      run: |
        npm ci --loglevel error
        npm run lint
        npm run testHeadless

    - name: Upload frontend coverage to Codecov
      run: |
        npm install codecov
        ./node_modules/.bin/codecov --token=eb122bec-04ed-41b9-ac86-74c3276a7d05 --file=ui/coverage/coverage-final.json

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.1.0
      with:
        mongodb-version: 3.6

    - name: Start Alfred
      run: |
        ./gradlew --build-cache bootRun &> /dev/null &
        echo -n "Waiting for boot to complete "
        while ! curl --output /dev/null --silent --head --fail http://localhost:8080; do echo -n "." && sleep 1; done
        echo " done!"
      env:
        SPRING_PROFILES_ACTIVE: test
        COMICS_COMICVINE_APIKEY: foo
        SPRING_DATA_MONGODB_URI: mongodb://localhost/alfred

    - name: Run end-to-end tests
      working-directory: ui
      run: npm run e2eHeadless

